//! Saved notes: every finished transcription is stored on disk.
//!
//! Layout (one directory per note, under the notes dir, default `~/.prata/notes`):
//!
//! ```text
//! <dir>/<id>/note.json     metadata + transcript segments
//! <dir>/<id>/audio.<ext>   the original upload / recording (kept for playback)
//! ```
//!
//! * Writes are atomic: `note.json` is written to a temporary file, fsynced and
//!   renamed over the old one. A new note is assembled in `.tmp-<id>/` and the whole
//!   directory is renamed into place, so a crash never leaves a half-written note.
//!   Deleting renames the directory to `.del-<id>` first, then removes it.
//! * IDs are generated by the server and validated on every request
//!   (`[a-z0-9-]`, 1–64 chars), so a request can never name a path outside the dir.
//! * All notes are indexed in memory at startup (a few KB each); listing and search
//!   work on that index.

use std::{
    collections::HashMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
    sync::Mutex,
};

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Segment {
    pub start: f64,
    pub end: f64,
    pub text: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Note {
    pub id: String,
    pub title: String,
    /// Unix seconds
    pub created: i64,
    pub model: String,
    pub audio_duration: f64,
    /// Original file name of the upload / recording
    pub filename: String,
    /// File name of the stored audio inside the note directory
    #[serde(default)]
    pub audio: Option<String>,
    #[serde(default)]
    pub audio_bytes: u64,
    #[serde(default)]
    pub backend: Option<String>,
    pub segments: Vec<Segment>,
}

impl Note {
    pub fn text(&self) -> String {
        let t: Vec<&str> = self.segments.iter().map(|s| s.text.trim()).filter(|s| !s.is_empty()).collect();
        t.join(" ")
    }
}

/// What the list endpoint returns per note.
#[derive(Clone, Debug, Serialize)]
pub struct Summary {
    pub id: String,
    pub title: String,
    pub created: i64,
    pub model: String,
    pub audio_duration: f64,
    pub words: usize,
    pub has_audio: bool,
    pub audio_bytes: u64,
    /// Start of the transcript, or the text around the first search hit
    pub snippet: String,
}

pub fn valid_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 64 && id.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

/// Content type for a stored audio file (by extension).
pub fn audio_mime(name: &str) -> &'static str {
    let ext = Path::new(name).extension().and_then(|e| e.to_str()).unwrap_or("").to_ascii_lowercase();
    match ext.as_str() {
        "m4a" | "mp4" | "aac" | "m4b" => "audio/mp4",
        "mp3" => "audio/mpeg",
        "wav" => "audio/wav",
        "ogg" | "oga" | "opus" => "audio/ogg",
        "webm" => "audio/webm",
        "flac" => "audio/flac",
        "mov" => "video/quicktime",
        "mkv" => "video/x-matroska",
        _ => "application/octet-stream",
    }
}

/// Sanitised file extension (alphanumeric, ≤ 8 chars), lowercase.
pub fn clean_ext(name: &str) -> String {
    let e: String = Path::new(name)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(8)
        .collect::<String>()
        .to_ascii_lowercase();
    if e.is_empty() { "bin".into() } else { e }
}

/// Title cleanup for rename: trimmed, no control characters, ≤ 200 chars.
pub fn clean_title(t: &str) -> Option<String> {
    let s: String = t.chars().map(|c| if c.is_control() { ' ' } else { c }).collect();
    let s = s.split_whitespace().collect::<Vec<_>>().join(" ");
    let s: String = s.chars().take(200).collect();
    (!s.is_empty()).then_some(s)
}

const MONTHS: [&str; 12] = ["jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec"];

/// Default title: local date and time plus the first words of the transcript,
/// e.g. "2 okt 2026 17:45 · Rödeby är en tätort i …".
pub fn default_title(created: i64, text: &str) -> String {
    use chrono::{Datelike, TimeZone, Timelike};
    let when = match chrono::Local.timestamp_opt(created, 0).single() {
        Some(d) => format!("{} {} {} {:02}:{:02}", d.day(), MONTHS[d.month0() as usize], d.year(), d.hour(), d.minute()),
        None => "Anteckning".into(),
    };
    let words: Vec<&str> = text.split_whitespace().collect();
    if words.is_empty() {
        return when;
    }
    let n = 6.min(words.len());
    let mut head = words[..n].join(" ");
    head = head.trim_end_matches(|c: char| c.is_ascii_punctuation() && c != '?' && c != '!').to_string();
    if words.len() > n {
        head.push_str(" …");
    }
    format!("{when} · {head}")
}

fn write_atomic(path: &Path, data: &[u8]) -> Result<()> {
    let dir = path.parent().context("no parent dir")?;
    let tmp = dir.join(format!(".{}.tmp", path.file_name().and_then(|n| n.to_str()).unwrap_or("f")));
    {
        let mut f = fs::File::create(&tmp).with_context(|| format!("create {}", tmp.display()))?;
        f.write_all(data)?;
        f.sync_all()?;
    }
    fs::rename(&tmp, path).with_context(|| format!("rename to {}", path.display()))?;
    if let Ok(d) = fs::File::open(dir) {
        let _ = d.sync_all(); // persist the rename (best effort)
    }
    Ok(())
}

/// Move a file, falling back to copy + remove across file systems.
fn move_file(from: &Path, to: &Path) -> Result<()> {
    if fs::rename(from, to).is_ok() {
        return Ok(());
    }
    fs::copy(from, to).with_context(|| format!("copy {} -> {}", from.display(), to.display()))?;
    fs::File::open(to).and_then(|f| f.sync_all()).ok();
    let _ = fs::remove_file(from);
    Ok(())
}

fn snippet_at(text: &str, byte_pos: usize, len: usize) -> String {
    // ~60 chars of context on each side, on char boundaries
    let start = text[..byte_pos].char_indices().rev().nth(60).map(|(i, _)| i).unwrap_or(0);
    let end_from = (byte_pos + len).min(text.len());
    let end = text[end_from..].char_indices().nth(80).map(|(i, _)| end_from + i).unwrap_or(text.len());
    let mut s = String::new();
    if start > 0 {
        s.push('…');
    }
    s.push_str(text[start..end].trim());
    if end < text.len() {
        s.push('…');
    }
    s
}

pub struct Store {
    dir: PathBuf,
    notes: Mutex<HashMap<String, Note>>,
}

impl Store {
    /// Open (and create) the notes directory and index every note in it.
    pub fn open(dir: impl Into<PathBuf>) -> Result<Self> {
        let dir = dir.into();
        fs::create_dir_all(&dir).with_context(|| format!("create notes dir {}", dir.display()))?;
        let mut notes = HashMap::new();
        for e in fs::read_dir(&dir)?.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            let p = e.path();
            if name.starts_with(".tmp-") || name.starts_with(".del-") {
                let _ = fs::remove_dir_all(&p); // leftovers of an interrupted create/delete
                continue;
            }
            if !valid_id(&name) || !p.is_dir() {
                continue;
            }
            match fs::read(p.join("note.json")).map_err(anyhow::Error::from).and_then(|b| Ok(serde_json::from_slice::<Note>(&b)?)) {
                Ok(n) if n.id == name => {
                    notes.insert(name, n);
                }
                Ok(_) => eprintln!("[notes] {}: id mismatch, skipped", p.display()),
                Err(e) => eprintln!("[notes] {}: unreadable note.json ({e}), skipped", p.display()),
            }
        }
        Ok(Self { dir, notes: Mutex::new(notes) })
    }

    pub fn dir(&self) -> &Path {
        &self.dir
    }

    pub fn len(&self) -> usize {
        self.notes.lock().unwrap().len()
    }

    /// Notes newest first. `q`: whitespace-separated terms, all must occur
    /// (case-insensitive) in the title or transcript.
    pub fn list(&self, q: Option<&str>) -> Vec<Summary> {
        let terms: Vec<String> = q.unwrap_or("").split_whitespace().map(|t| t.to_lowercase()).collect();
        let notes = self.notes.lock().unwrap();
        let mut v: Vec<(i64, String, Summary)> = notes
            .values()
            .filter_map(|n| {
                let text = n.text();
                let snippet;
                if terms.is_empty() {
                    snippet = text.chars().take(160).collect::<String>() + if text.chars().count() > 160 { "…" } else { "" };
                } else {
                    let hay = format!("{}\n{}", n.title, text).to_lowercase();
                    if !terms.iter().all(|t| hay.contains(t.as_str())) {
                        return None;
                    }
                    // snippet around the first term found in the transcript (lowercasing
                    // can change byte lengths; fall back to the start then)
                    let lt = text.to_lowercase();
                    snippet = match terms.iter().find_map(|t| lt.find(t.as_str()).map(|i| (i, t.len()))) {
                        Some((i, l)) if lt.len() == text.len() && text.is_char_boundary(i) => snippet_at(&text, i, l),
                        _ => text.chars().take(160).collect(),
                    };
                }
                Some((
                    n.created,
                    n.id.clone(),
                    Summary {
                        id: n.id.clone(),
                        title: n.title.clone(),
                        created: n.created,
                        model: n.model.clone(),
                        audio_duration: n.audio_duration,
                        words: text.split_whitespace().count(),
                        has_audio: n.audio.is_some(),
                        audio_bytes: n.audio_bytes,
                        snippet,
                    },
                ))
            })
            .collect();
        v.sort_by(|a, b| b.0.cmp(&a.0).then(b.1.cmp(&a.1)));
        v.into_iter().map(|x| x.2).collect()
    }

    pub fn get(&self, id: &str) -> Option<Note> {
        if !valid_id(id) {
            return None;
        }
        self.notes.lock().unwrap().get(id).cloned()
    }

    /// Store a new note; `audio` (if given) is moved into the note directory.
    pub fn create(&self, mut note: Note, audio: Option<&Path>) -> Result<Note> {
        if !valid_id(&note.id) {
            bail!("invalid note id");
        }
        let final_dir = self.dir.join(&note.id);
        if final_dir.exists() || self.notes.lock().unwrap().contains_key(&note.id) {
            bail!("note {} already exists", note.id);
        }
        let tmp = self.dir.join(format!(".tmp-{}", note.id));
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp)?;
        let res: Result<()> = (|| {
            if let Some(src) = audio {
                let name = format!("audio.{}", clean_ext(&note.filename));
                move_file(src, &tmp.join(&name))?;
                note.audio_bytes = fs::metadata(tmp.join(&name)).map(|m| m.len()).unwrap_or(0);
                note.audio = Some(name);
            }
            write_atomic(&tmp.join("note.json"), &serde_json::to_vec_pretty(&note)?)?;
            fs::rename(&tmp, &final_dir)?;
            if let Ok(d) = fs::File::open(&self.dir) {
                let _ = d.sync_all();
            }
            Ok(())
        })();
        if let Err(e) = res {
            let _ = fs::remove_dir_all(&tmp);
            return Err(e);
        }
        self.notes.lock().unwrap().insert(note.id.clone(), note.clone());
        Ok(note)
    }

    /// Change the title. `Ok(None)` if the note doesn't exist.
    pub fn rename(&self, id: &str, title: &str) -> Result<Option<Note>> {
        let Some(title) = clean_title(title) else { bail!("empty title") };
        if !valid_id(id) {
            return Ok(None);
        }
        let mut notes = self.notes.lock().unwrap();
        let Some(n) = notes.get(id) else { return Ok(None) };
        let mut n = n.clone();
        n.title = title;
        write_atomic(&self.dir.join(id).join("note.json"), &serde_json::to_vec_pretty(&n)?)?;
        notes.insert(id.to_string(), n.clone());
        Ok(Some(n))
    }

    /// Delete a note and its audio. Returns false if it didn't exist.
    pub fn delete(&self, id: &str) -> Result<bool> {
        if !valid_id(id) {
            return Ok(false);
        }
        let mut notes = self.notes.lock().unwrap();
        if notes.remove(id).is_none() {
            return Ok(false);
        }
        let dir = self.dir.join(id);
        let gone = self.dir.join(format!(".del-{id}"));
        let _ = fs::remove_dir_all(&gone);
        if let Err(e) = fs::rename(&dir, &gone) {
            // put it back in the index if we couldn't touch it
            if let Ok(n) = fs::read(dir.join("note.json")).map_err(anyhow::Error::from).and_then(|b| Ok(serde_json::from_slice::<Note>(&b)?)) {
                notes.insert(id.to_string(), n);
            }
            return Err(e.into());
        }
        fs::remove_dir_all(&gone)?;
        Ok(true)
    }

    /// Path and content type of a note's audio file.
    pub fn audio_path(&self, id: &str) -> Option<(PathBuf, &'static str)> {
        let n = self.get(id)?;
        let name = n.audio?;
        if name.contains('/') || name.contains('\\') || name.starts_with('.') {
            return None;
        }
        let p = self.dir.join(id).join(&name);
        p.is_file().then(|| (p, audio_mime(&name)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    pub fn note(id: &str, created: i64, text: &str) -> Note {
        Note {
            id: id.into(),
            title: default_title(created, text),
            created,
            model: "small".into(),
            audio_duration: 3.5,
            filename: "inspelning.m4a".into(),
            audio: None,
            audio_bytes: 0,
            backend: None,
            segments: vec![Segment { start: 0.0, end: 3.5, text: text.into() }],
        }
    }

    #[test]
    fn ids_are_validated() {
        assert!(valid_id("a1b2c3d4e5f6"));
        for bad in ["", "..", "../x", "a/b", "A1", "x.json", "a\\b", &"a".repeat(65)] {
            assert!(!valid_id(bad), "{bad}");
        }
    }

    #[test]
    fn create_list_search_rename_delete_and_reopen() {
        let tmp = tempfile::tempdir().unwrap();
        let st = Store::open(tmp.path()).unwrap();
        let audio = tmp.path().join("upload.m4a");
        fs::write(&audio, b"fake audio").unwrap();
        st.create(note("aaa111", 100, "Hej och välkommen till mötet"), Some(&audio)).unwrap();
        st.create(note("bbb222", 200, "Rödeby är en tätort i Blekinge"), None).unwrap();
        assert!(!audio.exists(), "audio was moved into the note");
        assert!(tmp.path().join("aaa111/audio.m4a").is_file());
        assert!(st.create(note("aaa111", 1, "dup"), None).is_err());

        let l = st.list(None);
        assert_eq!(l.iter().map(|s| s.id.as_str()).collect::<Vec<_>>(), ["bbb222", "aaa111"]);
        assert_eq!(l[1].audio_bytes, 10);
        assert_eq!(st.list(Some("RÖDEBY blekinge")).len(), 1);
        assert_eq!(st.list(Some("mötet"))[0].id, "aaa111");
        assert!(st.list(Some("finns inte")).is_empty());

        assert_eq!(st.rename("aaa111", "  Nytt\nnamn ").unwrap().unwrap().title, "Nytt namn");
        assert!(st.rename("aaa111", "   ").is_err());
        assert!(st.rename("zzz", "x").unwrap().is_none());
        assert_eq!(st.list(Some("nytt")).len(), 1, "title is searchable");

        // persists across restarts
        drop(st);
        let st = Store::open(tmp.path()).unwrap();
        assert_eq!(st.len(), 2);
        assert_eq!(st.get("aaa111").unwrap().title, "Nytt namn");
        let (p, mime) = st.audio_path("aaa111").unwrap();
        assert_eq!((fs::read(p).unwrap(), mime), (b"fake audio".to_vec(), "audio/mp4"));

        assert!(st.delete("aaa111").unwrap());
        assert!(!st.delete("aaa111").unwrap());
        assert!(!tmp.path().join("aaa111").exists(), "audio removed too");
        assert!(!st.delete("../bbb222").unwrap());
        drop(st);
        assert_eq!(Store::open(tmp.path()).unwrap().len(), 1);
    }

    #[test]
    fn leftovers_and_garbage_are_ignored() {
        let tmp = tempfile::tempdir().unwrap();
        fs::create_dir_all(tmp.path().join(".tmp-abc")).unwrap();
        fs::create_dir_all(tmp.path().join("broken")).unwrap();
        fs::write(tmp.path().join("broken/note.json"), b"{not json").unwrap();
        fs::create_dir_all(tmp.path().join("Weird.Name")).unwrap();
        let st = Store::open(tmp.path()).unwrap();
        assert_eq!(st.len(), 0);
        assert!(!tmp.path().join(".tmp-abc").exists());
    }

    #[test]
    fn titles() {
        let t = default_title(0, "Rödeby är en tätort i Rödeby församling i Karlskrona kommun.");
        assert!(t.ends_with(" · Rödeby är en tätort i Rödeby …"), "{t}");
        assert!(t.contains("1970") || t.contains("1969"));
        assert_eq!(clean_title("a\tb\u{0}c"), Some("a b c".into()));
        assert_eq!(audio_mime("x.M4A"), "audio/mp4");
        assert_eq!(clean_ext("../../etc/passwd"), "bin");
        assert_eq!(clean_ext("rec.MP4"), "mp4");
    }
}
